name: CMA Tech Blog
description: Web-related news and how-to's from Creative Media Alliance. Built with LESS on Jekyll and Github Pages.
baseurl:

# site runs locally at localhost:4000 when you run `jekyll serve --watch`
port:  4000

# ensure UTF-8 character encoding. Be sure to add <meta charset="utf-8"> as well!
encoding: utf-8

# include Pygments for syntax highlighting
pygments: true

# markdown editor default
markdown: kramdown
